name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3  # Using v3 for consistency
      with:
        go-version: 1.23  # Ensure Go 1.23 is used

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          $GOPATH/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: |
        go mod tidy  # Ensures dependencies are up to date

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run linters
      run: golangci-lint run ./...  # Lint all Go files in the repository

    - name: Run SAST (semgrep)
      run: semgrep --config auto .

    - name: Build binary
      run: go build -o main .

