name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build binary
      run: go build -o main .

    - name: Upload binary as release asset
      uses: actions/upload-artifact@v2
      with:
        name: main
        path: ./main

