name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Ensure consistency with actions/checkout v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'  # Ensure Go 1.23 is used
    
    - name: Clear Go cache (if any)
      run: |
        # Clear any existing Go version cache that might be interfering
        rm -rf $GOPATH/pkg/mod
        rm -rf $HOME/.cache/go-build
        echo "Go cache cleared"
    
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0  # Use a fixed version to avoid "latest"

    - name: Build binary
      run: go build -o main .

    - name: Upload binary as release asset
      uses: actions/upload-artifact@v2
      with:
        name: main
        path: ./main

    - name: Trigger Deployment Repository
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.REPO_DEPLOY_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/MCMXCIII/go-app-container/dispatches \
          -d '{"event_type": "build_container"}'

